### ISSUE TITLE
Is this book already published?

### ISSUE THREAD

**Issue by JayAhn2** [PacktPublishing/Up-and-Running-with-jOOQ#2]
I would like to read this book. and I would like to know whether the book for this repo is already published :) 
(Kudo: I love your book. Spring Boot Persistence Best Practice !)

**Comment by AnghelLeonard** [comment]
Hi,

Thank you for the nice words. I'm glad that you liked my book about Spring Boot Persistence, and I'm sure that you'll love this one and you'll become a jOOQ fan. 
This jOOQ book is not published yet. Most probably, this spring (March/April) will be the big release. I'll let you know :)

Thanks,
Anghel
